set SETUP_DIR=C:\Temp\WTT2025
set TOOLS_DIR=tools
set EXAMPLES_DIR=examples
set GAME_DIR=game
set LOVE_ZIP_FILE=love-11.5-win64
set ZEROBRANE_ZIP_FILE=ZeroBraneStudioEduPack-2.01-win32
set EXAMPLES_ZIP_FILE=wtt2025_gamedev_lua_examples
set GAME_ZIP_FILE=PONG
mkdir %SETUP_DIR%
mkdir %SETUP_DIR%\%ZEROBRANE_ZIP_FILE%
mkdir %SETUP_DIR%\%EXAMPLES_DIR%
mkdir %SETUP_DIR%\%GAME_DIR%
tar xvf %TOOLS_DIR%\%LOVE_ZIP_FILE%.zip -C %SETUP_DIR%
tar xvf %TOOLS_DIR%\%ZEROBRANE_ZIP_FILE%.zip -C %SETUP_DIR%\%ZEROBRANE_ZIP_FILE%
tar xvf %EXAMPLES_DIR%\%EXAMPLES_ZIP_FILE%.zip -C %SETUP_DIR%\%EXAMPLES_DIR%
tar xvf %GAME_DIR%\%GAME_ZIP_FILE%.zip -C %SETUP_DIR%\%GAME_DIR%
cd %SETUP_DIR%